# Generated by Django 2.1.4 on 2019-01-09 11:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an author (arhitect) name', max_length=200)),
                ('register_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['register_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a company name', max_length=200)),
                ('register_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['register_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FormFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular form factor across whole catalog', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('finalized', models.BooleanField(default=False, help_text='True, if this is moderated finalised formfactor')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('ancestor_id', models.UUIDField(null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
                ('company_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.CompanyUser')),
            ],
            options={
                'ordering': ['release_date'],
            },
        ),
        migrations.CreateModel(
            name='Private_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a private user name', max_length=200)),
                ('register_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['register_date', 'name'],
            },
        ),
        migrations.AddField(
            model_name='formfactor',
            name='private_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Private_user'),
        ),
    ]
