# Generated by Django 2.1.4 on 2019-01-09 11:42

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Private_user',
            new_name='PrivateUser',
        ),
    ]
