# Generated by Django 2.1.4 on 2019-01-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190109_1442'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormFactor',
            new_name='Plan',
        ),
    ]
