# Generated by Django 2.1.4 on 2019-01-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20190116_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['approve_date'], 'permissions': (('can_mark_approved', 'Can set plan as approved'), ('can_create_plan', 'Can create plan'))},
        ),
    ]
