# Generated by Django 2.1.4 on 2019-01-16 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20190116_1348'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['approve_date'], 'permissions': (('can_mark_approved', 'Can set plan as approved'), ('can_create_plan', 'Can create plan'), ('can_apply_plan', 'Can apply plan'))},
        ),
        migrations.AddField(
            model_name='plan',
            name='creation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
