# Generated by Django 2.1.4 on 2019-01-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20190116_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='ancestor_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
