# Generated by Django 2.1.4 on 2019-01-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20190117_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('axis_id', models.IntegerField()),
                ('x0', models.IntegerField()),
                ('y0', models.IntegerField()),
                ('x1', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('rx', models.IntegerField()),
                ('ry', models.IntegerField()),
                ('align', models.CharField(blank=True, choices=[('l', 'Left'), ('r', 'Right'), ('c', 'Center'), ('a', 'Auto')], default='c', help_text='You can explicitly specify alignment option. Default = Auto', max_length=1)),
            ],
        ),
    ]
