# Generated by Django 2.1.4 on 2019-01-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_element'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['approve_date'], 'permissions': (('can_mark_approved', 'Can set plan as approved'), ('can_edit_plan', 'Can edit plan'), ('can_apply_plan', 'Can apply plan'))},
        ),
        migrations.AlterField(
            model_name='element',
            name='x0',
            field=models.IntegerField(default=50),
        ),
    ]
