# Generated by Django 2.1.4 on 2019-01-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='plan',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
